# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-27 17:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_psw_services'),
    ]

    operations = [
        migrations.CreateModel(
            name='Broker',
            fields=[
                ('brokerID', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('ip', models.CharField(max_length=15, unique=True)),
                ('description', models.CharField(blank=True, max_length=250)),
                ('createdOn', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.User')),
            ],
        ),
        migrations.RenameModel(
            old_name='Services',
            new_name='Service',
        ),
        migrations.RemoveField(
            model_name='psw',
            name='user',
        ),
        migrations.DeleteModel(
            name='PSW',
        ),
    ]
